apiVersion: v1
kind: Service
metadata:
  name: nlp-analyzer
  labels:
    app: nlp-analyzer
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: nlp-analyzer
  type: ClusterIP